# Generated by Django 4.2.5 on 2024-04-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_booking_check_in_date_booking_check_out_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number_of_adult',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_children',
            field=models.IntegerField(default=0),
        ),
    ]
