# Generated by Django 4.2.5 on 2024-05-27 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_payment_payment_date_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='display_on_website',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 27, 4, 56, 26, 225394, tzinfo=datetime.timezone.utc)),
        ),
    ]
