# Generated by Django 4.2.5 on 2024-03-27 06:41

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_room_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='features',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
