# Generated by Django 4.2.5 on 2024-03-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_room_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='features',
            field=models.CharField(max_length=200),
        ),
    ]
