# Generated by Django 4.2.5 on 2024-04-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_room_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='availability',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.CharField(max_length=10),
        ),
    ]
