# Generated by Django 4.2.5 on 2024-04-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_room_availability_alter_room_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='max_room',
            field=models.IntegerField(default=5),
        ),
    ]
