# Generated by Django 4.2.5 on 2024-04-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_room_max_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='number_of_adult',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='number_of_children',
            field=models.IntegerField(default=0),
        ),
    ]
